# Generated by Django 4.1.7 on 2023-02-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='some_value', max_length=300, verbose_name='Описание'),
        ),
    ]
